// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
        case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaOMRwfCw7es3kZT3Gz9tRQ9ft6qVWMDk',
    appId: '1:796286049:android:24e1380737e5b2793e5e20',
    messagingSenderId: '796286049',
    projectId: 'ellenatodo',
   authDomain: 'metro-auth-20cc7.firebaseapp.com',
    storageBucket: 'metro-auth-20cc7.appspot.com',
    measurementId: 'G-4YF5CTNDGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaOMRwfCw7es3kZT3Gz9tRQ9ft6qVWMDk',
    appId: '1:796286049:android:24e1380737e5b2793e5e20',
    messagingSenderId: '796286049',
    projectId: 'ellenatodo',
    storageBucket: 'metro-auth-20cc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaOMRwfCw7es3kZT3Gz9tRQ9ft6qVWMDk',
    appId: '1:688917138939:ios:6e4473c3a63b5ce3114f5e',
    messagingSenderId: '796286049',
    projectId: 'ellenatodo',
    storageBucket: 'metro-auth-20cc7.appspot.com',
    iosBundleId: 'com.example.loginMetro',
  );

}
